apiVersion: v1
kind: ConfigMap
metadata:
  name: laravel-config
  labels:
    name: laravel-config
data:
  APP_ENV: "local"
  APP_KEY: "base64:vw6G2uP8LV22haEERtzr5yDCBraLrMwbxlbSJDA97uk="
  APP_DEBUG: "true"
  APP_LOG: "errorlog"
  APP_LOG_LEVEL: "debug"
  APP_URL: "http://localhost"

  DB_PORT: "3306"
  DB_HOST: "mysql-master-service"
  DB_DATABASE: "joantest"
  DB_USERNAME: "root"
  DB_PASSWORD: "secret"
  DB_CONNECTION: "mysql"

  REDIS_HOST: "redis-master-service"
  REDIS_PASSWORD: "test"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
