name: deploy-laravel

on:
  push:
    branches:
      - master
    paths:
      - 'laravel-test/**'

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - run: cd laravel-test && docker build -t rdjoan001/laravel .
        - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          env:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        - run: docker push rdjoan001/laravel
        - uses: digitalocean/action-doctl@v2
          with:
            token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        - run: doctl kubernetes cluster kubeconfig save k8s-test
        - run: kubectl rollout restart deployment laravel-depl
            
