name: deploy-nodejs-chat

on:
  push:
    branches:
      - master
    paths:
      - 'nodejs-test/**'

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - run: cd nodejs-test && docker build -t rdjoan001/nodejs-chat .
        - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          env:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        - run: docker push rdjoan001/nodejs-chat
        - uses: digitalocean/action-doctl@v2
          with:
            token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        - run: doctl kubernetes cluster kubeconfig save k8s-test
        - run: kubectl rollout restart deployment nodejs-chat-depl
            
